### ISSUE TITLE
nil receivers do not panic

### ISSUE THREAD

**Issue by tep** [Pungyeon/clean-go-article#15]
In the first paragraph of the section discussing [Nil Values](https://github.com/Pungyeon/clean-go-article#nil-values) you state, "Things break, when you try to access methods or properties of a nil value." _This is only partially true_.

While attempting to access a struct member from a nil pointer will always cause a panic, calling a method on a nil receiver is perfectly acceptable (and can often prove to be quite useful).

Here's an example [[Playground Link](https://play.golang.org/p/g7UdiI9JPT8)]:

```go
package main

import (
	"fmt"
)

func main() {
	var f *foo

	fmt.Println("One:", f.method())

	f = new(foo)

	fmt.Println("Two:", f.method())
}

type foo struct{}

func (f *foo) method() string {
	if f == nil {
		return "foo is nil"
	}
	return "good foo"
}
```

...which emits:
```
One: foo is nil
Two: good foo
```

**Comment by Pungyeon** [comment]
This is excellent feedback.... I didn't actually know that this was possible. I will make sure to add this to the change list 😃
