### ISSUE TITLE
Suggestion: Update repo description.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [Pungyeon/clean-go-article#21]
Hey Pungyeon! I think we should also update the repo's description to maybe read something like this:

> A reference for the Go community that aims to help developers write cleaner code. Begins with a short introduction to the fundamentals of writing clean code and discusses concrete refactoring examples specific to Go.

Let me know what you think. Thanks!

**Comment by Pungyeon** [comment]
I think that is a good idea. Do you feel the following sentence is too long?

> A reference for the Go community, which aims to help developers write cleaner code, containing both a short introduction to the fundamentals of writing clean code and concrete refactoring examples, specific to Go.

**Comment by AleksandrHovhannisyan** [comment]
Yep, that's a bit too long, imo. If you want one sentence, we can cut some stuff:

> A reference for the Go community that covers the fundamentals of writing clean code and discusses concrete refactoring examples specific to Go.

What do you think?

**Comment by Pungyeon** [comment]
Done. 👍
