### ISSUE TITLE
re:reading clean-go-article

### ISSUE THREAD

**Issue by butuzov** [Pungyeon/clean-go-article#28]
I have started reading the article, and some of the examples make me question myself. Just to be clear - I am just starting writing Go code, and  I clearly understand what you talking about, the only thing I found weirds is some of the codes provided for examples. I am not making any PR because I am not sure it's required and I currently fully understand code (or maybe its some jedy tricks that don't work for people like me). 

1. Returning Dynamic Errors (a)

`Type()` returns an error? Or casted to a string? 
if `errDetails.details` is string, why do we use empty interface?

```go
// ---- before 
type ErrorDetails interface {
    Error() string
    Type() string
}

type errDetails struct {
    errtype error
    details string
}

func NewErrorDetails(err error, details ...interface{}) ErrorDetails {
    return &errDetails{
        errtype: err,
        details: details,
    }
}

func (err *errDetails) Error() string {
    return fmt.Sprintf("%v: %v", err.errtype, err.details)
}

func (err *errDetails) Type() error {
    return err.errtype
}

// ---- after 
type ErrorDetails interface {
	Error() string
	Type() error
}

type errDetails struct {
	errtype error
	details string
}

func NewErrorDetails(err error, details string) ErrorDetails {
	return &errDetails{
		errtype: err,
		details: details,
	}
}

func (err *errDetails) Error() string {
	return fmt.Sprintf("%v: %v", err.errtype, err.details)
}

func (err *errDetails) Type() error {
	return err.errtype
}
```

2. Returning Dynamic Errors (b)

Should code actually represent the usage of typed error `NewErrorDetails`?

```go
// current code
func (store *Store) GetItem(id string) (Item, error) {
    store.mtx.Lock()
    defer store.mtx.Unlock()

    item, ok := store.items[id]
    if !ok {
        return NullItem, fmt.Errorf("Could not find item with ID: %s", id)
    }
    return item, nil
}

// fixed? missing  actually `NewErrorDetails`
func (store *Store) GetItem(id string) (Item, error) {
    store.mtx.Lock()
    defer store.mtx.Unlock()

    item, ok := store.items[id]
    if !ok {
        return NullItem, NewErrorDetails(errors.New("Could not find item with ID"), "1")
    }
    return item, nil
}
```

3. Function Length 

`GetItem` doesn't looks right, While `getReference` is valid check and syntax. `ref` unused, `ok` not checked.

```go 
func GetItem(extension string) (Item, error) {
    if ref, ok := getReference(extension) {
        return EmptyItem, ErrReferenceNotFound
    }
    return getItemByReference(ref)
}

func getReference(extension string) (string, bool) {
    refIface, ok := db.ReferenceCache.Get(extension)
    if !ok {
        return EmptyItem, false
    }
    return refIface.(string)
}
```

---

I haven't finished reading the article yet. And sorry for troubling you.

**Comment by Pungyeon** [comment]
1. Good catch... yeah, either `details` should be an interface slice or we should just accept `string`... I will correct this asap.

2. Not sure I understand this question... but I can see that there is an error as well here the "1" should be `id` instead

3. Oh wow... yeah, this would get a compiler error for sure. It should be:

```go 
ref, ok := getReference(extension)
if !ok {
```

Thanks for the feedback, really appreciate it!

**Comment by hugecannon** [comment]
@Pungyeon I believe the second point @butuzov was making was that you didn't include the updated code in your section [Returning Dynamic Errors](https://github.com/Pungyeon/clean-go-article#returning-dynamic-errors)

You introduce the concept of `ErrorDetails` type, but the `GetItem` function still returns a plain `fmt.Errorf`

**Comment by Pungyeon** [comment]
@hugecannon Thanks! I will fix this as soon as I have time 👍

**Comment by Pungyeon** [comment]
thu

**Comment by Pungyeon** [comment]
Finally fixed 😅
