### ISSUE TITLE
Inverted bool checks

### ISSUE THREAD

**Issue by muesli** [Pungyeon/clean-go-article#30]
```
if ref, ok := refIface.(string); ok {
        // return cast error on reference 
}
```

It seems to me, that this logic is inverted. Shouldn't it read `!ok`? The same actually applies for pretty much all `ok` checks below.

**Comment by Pungyeon** [comment]
You are right, I will change this.

**Comment by Pungyeon** [comment]
Changes are here, give a 👍 if you approve 😄 

#31 

Thanks so much for pointing this out! 🙏
