### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by yuyongbo** [Pungyeon/clean-go-article#4]
Hello, can I translate this article into Chinese? thanks

**Comment by Pungyeon** [comment]
Of course you can! That would be amazing!!

**Comment by Pungyeon** [comment]
Any update on this @yuyongbo ?

**Comment by yuyongbo** [comment]
I'm sorry, wait for me for two weeks. I'm a little busy these days,I will submit a chinese translation

**Comment by Pungyeon** [comment]
No need to apologise! I'm just super excited and just wanted to know what the status was 😄 There is no hurry... I am just honoured that someone would want to translate this !

**Comment by yuyongbo** [comment]
Aha,That's good, I'll finish it as soon as possible.  😄

**Comment by ka2u** [comment]
Hi, I want to translate this article into Japanese.
Can you give me permission to translate?

**Comment by Pungyeon** [comment]
@ka2u That sounds awesome! Just keep me updated on the progress. You have my full permission 🙏

**Comment by ka2u** [comment]
@Pungyeon Thank you!
I did not publish it, but it was already translated.
Released it now.
https://github.com/ka2u/clean-go-article-japanese

**Comment by Pungyeon** [comment]
Amazing! Thank you @ka2u 🙏
