### ISSUE TITLE
May I contribute edits to the README to clarify some of the writing?

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [Pungyeon/clean-go-article#5]
Hey Pungyeon!

I came across your repo today and was wondering if you'd be cool with me making some edits to the writing to make things clearer. 

For example, I was reading over this bit on test-driven development:

> The core of creating clean code stems from creating good tests. Writing good tests helps create clean code, as it invites developers to think about the outcomes and test coverage of functions / functionality. It's easier to test a function that is only 4 lines, rather than a function, which is 40. In the same manner, a function which is 4 lines, is typically easier to understand than a function of 40 lines. Therefore, when using test driven development, the resulting code is much more likely to be of a cleaner nature.

I think we could reword this more concisely like so:

> Test-driven development contributes to code cleanliness by inviting developers to frequently evaluate the functionality and purpose of their code. To make testing easier, developers are encouraged to write short functions that only do one thing. It's certainly easier to test (and understand) a function that's only 4 lines long than one that's 40, for example.

If you're okay with it, I'd be happy to make a PR with some fixes like that :)

**Comment by Pungyeon** [comment]
Absolutely! Start a PR and I will review & merge as soon as I have the time. Thank you so much, that's excellent feedback 🙏

**Comment by Pungyeon** [comment]
Thank you so much, again, for this contribution 💪 

I have merged the PR. The changes were great, so I am just going to close this Issue 😄
