### ISSUE TITLE
GetItem* is not an idiomatic method name

### ISSUE THREAD

**Issue by prestonvanloon** [Pungyeon/clean-go-article#6]
See  https://golang.org/doc/effective_go.html#Getters

Snippet:

> Go doesn't provide automatic support for getters and setters. There's nothing wrong with providing getters and setters yourself, and it's often appropriate to do so, but it's neither idiomatic nor necessary to put Get into the getter's name. If you have a field called owner (lower case, unexported), the getter method should be called Owner (upper case, exported), not GetOwner. The use of upper-case names for export provides the hook to discriminate the field from the method. A setter function, if needed, will likely be called SetOwner.

**Comment by Pungyeon** [comment]
Just skimming through the article again, I don't see the `GetItem` method / function name being used as a getter, but a separate method or function. I feel that it's fine having these be prefixed with `Get`... but I am not 100% set on this. What are your thoughts?

**Comment by prestonvanloon** [comment]
@Pungyeon That's a good point actually. I'd agree with you but slightly leaning towards removing Get for consistency. It's not a hard rule and there are some times when it makes more sense to keep Get.

There is one change I would recommend, you have a line that is a getter with `Get`

```go
db.GetItem(order.ItemID)
```

Thanks for putting this together by the way. Great stuff :)

**Comment by prestonvanloon** [comment]
There's also a few more getters with Get, I won't list all of them but if you search for "GetItem" you'll see a few.

```go
func (store *Store) GetItem(id string) (Item, error) 
```

**Comment by Pungyeon** [comment]
Perhaps we have differing opinions on the definition of `getter`'s?

My understanding is that a getter is a method, with the sole purpose of returning a `struct` property. Such as:

```go
type Item struct {
  text string
}

func (item *Item) Text() string {
  return item.text
}
```

So, I don't feel that the function which you pointed to, is a `getter`, considering that it's a method on a store, much like a database. Since this isn't returning a property, but an item from a store, I feel that the `Get` is clear for it's intentions. 

Perhaps the `Item` should be stripped instead, as to fulfilling an interface such as:

```go
type ItemStore interface {
  Get(id int64) (Item, error)
  Put(Item) error
  Delete(id int64) error
  Update(Item) error
}
```

Honestly, the only reason for the name `GetItem` is for local clarity, so I wouldn't have to explain the above in advance…. But maybe this is misleading?

**Comment by prestonvanloon** [comment]
> So, I don't feel that the function which you pointed to, is a getter, considering that it's a method on a store, much like a database. Since this isn't returning a property, but an item from a store, I feel that the Get is clear for it's intentions.

This requires some knowledge of the underlying implementation. For all I know (or care) the property I am getting could be a struct property or stored on disk. It shouldn't matter. If I am getting a resource from something, the method is a "getter". 

For your item store, that looks good to me. It is often worth the abstraction on map access with you might be accessing from multiple threads.

**Comment by AleksandrHovhannisyan** [comment]
I'm personally torn on this one but am leaning towards `GetItem`. I usually prefer to prefix getters with `Get` to make my intentions clearer. [This old SO post](https://stackoverflow.com/a/2648535/5323344) provides a good reason in favor of the `Get` prefix: function names should be verbs. Thus, `Item` is not a particularly informative function name—what about the item? In the usage context, it will be somewhat obvious that you're _getting_ the item, but why not make that 100% clear in the function signature?

[Another answer](https://stackoverflow.com/a/2648549/5323344) on that same question makes a note about consistency: if you don't use `Get` for the getter, there's no good reason to justify using `Set` for the setter. And in that case, you end up with overloaded functions with the same name.

**Comment by Pungyeon** [comment]
I will close this, I think we just semantically disagree. I like the point made above by @AleksandrHovhannisyan. Of course, anyone is welcome to re-open this issue 🙏
